development:
    dialect: postgres
    datasource: postgresql://postgres:postgres@localhost:5432/bitlytest?sslmode=disable
    dir: migrations/

production:
    dialect: postgres
    datasource: dbname=bitlytest sslmode=disable host=localhost user=postgres
    dir: migrations/postgres
    table: migrations